# Python Fundamentals & Pandas Basics
This notebook covers the basic Python syntax and an introduction to the pandas library.

# A. Looking Under the Hood

In Notebook 1 you successfully imported local data, pulled data from GitHub, and even Queried a World Bank API! You used strings, lists, and variables to do it. Now, we are going to look under the hood at the exact 'grammar' of what you just built.

## A. Note for R-users

- Python is in many ways similiar to R

- Comment code: #
- Some functions are exactly the same: print()
- Saving an object requires you to write a name and set it equal to whatever object you are interested in saving
- You must run the code in the correct order
- We use libraries!

In [1]:
# REMEMBER THIS IS WHAT WE USED BEFORE
# This line saves the web address (URL) of the World Bank data file as text in a variable named 'url'.
url = "https://github.com/Data-Science-Public-Policy/graspp_2025_spring/raw/refs/heads/module_1/data/examples/module_1/world_bank_data.csv"

In [2]:
# This is a comment
print('This is a print function')

This is a print function

In [3]:
saved_object = 'hello world'
print(saved_object)

hello world

In [4]:
saved_object = 'GRASPP IS COOL'
saved_object

'GRASPP IS COOL'

## A.1 Strings

- Think of it as a piece data that has quotes
- R-users: This is the same as in R!

In [3]:
my_str = 'Python is cool'
print(my_str)

Python is cool

### A.1.1 This function can tell us what type our object is

In [4]:
type(my_str)

str

### A.1.2 Overwriting

In [5]:
my_str = 'Python is NOT cool'
my_str

'Python is NOT cool'

## A.2 Integers/Float

In [8]:
my_num = 100
type(my_num)

int

In [6]:
my_num = 100.9483859390942949
type(my_num)

float

## A.3 Dictionaries

In [9]:
rename_country_map = {
    "Canada": "Canada",
    "Mexico": "Republic of Mexico",
    "United States": "United States of America",
    "Germany": "Federal Republic of Germany",
}

In [10]:
rename_country_map.values()

dict_values(['Canada', 'Republic of Mexico', 'United States of America', 'Federal Republic of Germany'])

In [11]:
rename_country_map.keys()

dict_keys(['Canada', 'Mexico', 'United States', 'Germany'])

# B. Introduction to Pandas

### For R users: Pandas is similar to DPLYR!

In general we use it to:

- Manipulate data (Today's topic)
- Viusualize our data (graphing etc.)
- Download data directly from the internet
- Build models (Regression, Machine learning, Neural Networks)

## B.A We must import the library before using!
- Again this is similar to R
- However unlike R: in order to use the functions (in general) we have to use an acronym to access the functions

In [6]:
import pandas as pd

## B.1 Import data
- pd.read_stata
- pd.read_csv
- pd.read_excel

In [7]:
url = "https://raw.githubusercontent.com/corybaird/datascience-publicpolicy-2026/refs/heads/main/data/examples/week_2/world_bank_data.csv"
df = pd.read_csv(url)

In [8]:
df

,Unnamed: 0,indicator,country,countryiso3code,date,value
0,0,GDP per capita (current US$),Canada,CAN,2023,53431.185706
1,1,GDP per capita (current US$),Canada,CAN,2022,55509.393176
2,2,GDP per capita (current US$),Canada,CAN,2021,52496.844169
3,3,GDP per capita (current US$),Japan,JPN,2023,33766.526825
4,4,GDP per capita (current US$),Japan,JPN,2022,34017.271808
5,5,GDP per capita (current US$),Japan,JPN,2021,40058.537328
6,6,GDP per capita (current US$),Mexico,MEX,2023,13790.024343
7,7,GDP per capita (current US$),Mexico,MEX,2022,11385.407076
8,8,GDP per capita (current US$),Mexico,MEX,2021,10314.050674
9,9,GDP per capita (current US$),United States,USA,2023,82769.412211
10,10,GDP per capita (current US$),United States,USA,2022,78035.175360
11,11,GDP per capita (current US$),United States,USA,2021,71318.307359

## B.3 Select and Filter

### B.3.1 Select column

In [24]:
df['country'].head(2)

0    Canada
1    Canada
Name: country, dtype: object

In [25]:
df.country.head(2)

0    Canada
1    Canada
Name: country, dtype: object

## B.3.2 Subset Rows

<img src="Screenshots/subset_row.svg" />

### B.3.2.1 Show unique values in a column

In [9]:
df.country.unique()

array(['Canada', 'Japan', 'Mexico', 'United States'], dtype=object)

In [27]:
df.date.unique()

array([2023, 2022, 2021])

#### B.3.2.2 Select Row

In [10]:
df.query("country == 'Japan'")

,Unnamed: 0,indicator,country,countryiso3code,date,value
3,3,GDP per capita (current US$),Japan,JPN,2023,33766.526825
4,4,GDP per capita (current US$),Japan,JPN,2022,34017.271808
5,5,GDP per capita (current US$),Japan,JPN,2021,40058.537328

In [11]:
df.query("date == 2022")

,Unnamed: 0,indicator,country,countryiso3code,date,value
1,1,GDP per capita (current US$),Canada,CAN,2022,55509.393176
4,4,GDP per capita (current US$),Japan,JPN,2022,34017.271808
7,7,GDP per capita (current US$),Mexico,MEX,2022,11385.407076
10,10,GDP per capita (current US$),United States,USA,2022,78035.175360

In [17]:
mask = df.country == 'Japan'
mask

0     False
1     False
2     False
3      True
4      True
5      True
6     False
7     False
8     False
9     False
10    False
11    False
Name: country, dtype: bool

In [18]:
df[mask]
df.loc[mask]

,Unnamed: 0,indicator,country,countryiso3code,date,value
3,3,GDP per capita (current US$),Japan,JPN,2023,33766.526825
4,4,GDP per capita (current US$),Japan,JPN,2022,34017.271808
5,5,GDP per capita (current US$),Japan,JPN,2021,40058.537328

#### B.2.2.3 Subset multiple conditions

In [69]:
df.query("country == 'Japan' & date>2021")

,Unnamed: 0,indicator,country,countryiso3code,date,value
3,3,GDP per capita (current US$),Japan,JPN,2023,33766.526825
4,4,GDP per capita (current US$),Japan,JPN,2022,34017.271808

#### B.3.2.4 Subset in a list

In [70]:
df.query("country in ['Japan', 'Mexico']")

,Unnamed: 0,indicator,country,countryiso3code,date,value
3,3,GDP per capita (current US$),Japan,JPN,2023,33766.526825
4,4,GDP per capita (current US$),Japan,JPN,2022,34017.271808
5,5,GDP per capita (current US$),Japan,JPN,2021,40058.537328
6,6,GDP per capita (current US$),Mexico,MEX,2023,13790.024343
7,7,GDP per capita (current US$),Mexico,MEX,2022,11385.407076
8,8,GDP per capita (current US$),Mexico,MEX,2021,10314.050674

### B.3.2.5 Subset rows and columns

In [71]:
df.query("country in ['Japan', 'Mexico']")[['country', 'date']]

  country  date
3   Japan  2023
4   Japan  2022
5   Japan  2021
6  Mexico  2023
7  Mexico  2022
8  Mexico  2021

## B.3 Rename 

### B.3.1 Rename columns

In [35]:
df.rename({"value" : "GDP"}, axis=1).head(2)

,Unnamed: 0,indicator,country,countryiso3code,date,GDP
0,0,GDP per capita (current US$),Canada,CAN,2023,53431.185706
1,1,GDP per capita (current US$),Canada,CAN,2022,55509.393176

### B.3.2 Rename rows

In [45]:
rename_country_map = {
    "Canada" : "O CANANDA"
}

df.country.replace(rename_country_map)
df.country.map(rename_country_map)

0     O CANANDA
1     O CANANDA
2     O CANANDA
3           NaN
4           NaN
5           NaN
6           NaN
7           NaN
8           NaN
9           NaN
10          NaN
11          NaN
Name: country, dtype: object

## B.4 Apply functions to pandas

### B.4.1 Basics

In [74]:
def basics(data):
    print('Head')
    print(data.head(2))
    print('')
    print('Tail')
    print(data.tail(2))
    print('')
    print('Columns')
    print(data.columns[:3])
    print('')
    print('Info')
    print(data.info())

basics(df)

Head
   Unnamed: 0                     indicator country countryiso3code  date  \
0           0  GDP per capita (current US$)  Canada             CAN  2023
1           1  GDP per capita (current US$)  Canada             CAN  2022

          value
0  53431.185706
1  55509.393176

Tail
    Unnamed: 0                     indicator        country countryiso3code  \
10          10  GDP per capita (current US$)  United States             USA
11          11  GDP per capita (current US$)  United States             USA

    date         value
10  2022  78035.175360
11  2021  71318.307359

Columns
Index(['Unnamed: 0', 'indicator', 'country'], dtype='str')

Info
<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       12 non-null     int64
 1   indicator        12 non-null     str
 2   country          12 non-null     str
 3   countryiso3code  12 non-null     str
 4   date             12 non-null     int64
 5   value            12 non-null     float64
dtypes: float64(1), int64(2), str(3)
memory usage: 708.0 bytes
None

### B.4.2 subset

In [75]:
def subset(countries, columns):
    out = df.query(f"country in {countries}")[columns]
    return out
subset(
    countries = ['Japan', 'Mexico'],
    columns = ['country', 'date']
)

  country  date
3   Japan  2023
4   Japan  2022
5   Japan  2021
6  Mexico  2023
7  Mexico  2022
8  Mexico  2021